Fix "error: a function declaration witho ut a prototype is deprecated in all versions of C"
/home/kevin/los21/kernel/xiaomi/sm8350/drivers/staging/qcacld-3.0/../qca-wifi-ho
st-cmn/hif/src/ce/ce_service_srng.c:1014:32: error: a function declaration witho
ut a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
struct ce_ops *ce_services_srng()
                               ^
                                void
1 error generated.