Fix "error: a function declaration  without a prototype is deprecated in all versions of C"
/home/kevin/los21/kernel/xiaomi/sm8350/drivers/staging/qcacld-3.0/components/pkt
_capture/core/src/wlan_pkt_capture_main.c:652:46: error: a function declaration 
without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototy
pes]
struct wlan_objmgr_vdev *pkt_capture_get_vdev()
                                             ^
                                              void
2 errors generated.