Fix "error: a function declaration  without a prototype is deprecated in all versions of C"
/home/kevin/los21/kernel/xiaomi/sm8350/drivers/staging/qcacld-3.0/../qca-wifi-ho
st-cmn/target_if/core/src/target_if_main.c:98:40: error: a function declaration 
without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototy
pes]
struct target_if_ctx *target_if_get_ctx()
                                       ^
                                        void
1 error generated.