Fix "a function declaration without a prototype is deprecated  in all versions of C"
/home/kevin/los21/kernel/xiaomi/sm8350/techpack/camera/drivers/cam_utils/cam_deb
ug_util.c:22:59: error: a function declaration without a prototype is deprecated
 in all versions of C [-Werror,-Wstrict-prototypes]
const struct camera_debug_settings *cam_debug_get_settings()
                                                          ^
                                                           void
1 error generated.